language: node_js
node_js:
  - 14
addons:
  packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - eslint 'src/**'
  - npm run test:cypress:ci
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: enquete-4dev-app
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
after_success:
  - npm run test:coveralls