language: node_js
node_js:
  - 14
script:
  - eslint 'src/**'
  - npm run test:coveralls
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: enquete-4dev-app
  skip_cleanup: true
  all_branches: true
